import wording from './wording'

const appConfig = {
  language: 'de',
  wording,
  wordingHandles: {
    title: 'app_title',
    itemLabel: 'items_label',
    downloadWithTimestamp: 'download_with_timestamp',
    uploadJson: 'upload_json',
    downloadJson: 'download_json',
    reset: 'reset',
    languageSwitchAria: 'language_switch_aria',
    languageButtonDe: 'language_button_de',
    languageButtonEn: 'language_button_en',
    noFileLoaded: 'no_file_loaded',
    searchLabel: 'search_label',
    searchPlaceholder: 'search_placeholder',
    unsavedChanges: 'unsaved_changes',
    configurationTitle: 'configuration_title',
    applyConfiguration: 'apply_configuration',
    downloadConfiguration: 'download_configuration',
    configFieldHeader: 'config_field_header',
    configTypeHeader: 'config_type_header',
    configLabelHeader: 'config_label_header',
    configPlaceholderHeader: 'config_placeholder_header',
    configTypeNormal: 'config_type_normal',
    configTypeText: 'config_type_text',
    configTypeInteger: 'config_type_integer',
    configTypeCheckbox: 'config_type_checkbox',
    configLabelInputPlaceholder: 'config_label_input_placeholder',
    configHintInputPlaceholder: 'config_hint_input_placeholder',
    listEmptyAfterUpload: 'list_empty_after_upload',
    noSearchResults: 'no_search_results',
    scanPreviewAlt: 'scan_preview_alt',
    scanUnavailable: 'scan_unavailable',
    sidebarPreviousItemAria: 'sidebar_previous_item_aria',
    sidebarNextItemAria: 'sidebar_next_item_aria',
    sidebarScanCounterPrefix: 'sidebar_scan_counter_prefix',
    sidebarCloseAria: 'sidebar_close_aria',
    statusFilePrefix: 'status_file_prefix',
    uploadPrompt: 'upload_prompt',
    fullscreen: 'fullscreen',
    close: 'close',
    lightboxImageAlt: 'lightbox_image_alt',
    resetConfirm: 'reset_confirm',
  },
  primaryColor: '#1f7a8c',
}

export default appConfig
